#!/usr/bin/env php
<?php 

require_once __DIR__.'/../vendor/autoload.php';
require_once __DIR__.'/../vendor/dg/twitter-php/src/twitter.class.php';

use Pogotc\MarkovGenerator;
use Symfony\Component\Yaml\Yaml;

$config = Yaml::parse(__DIR__.'/../config/config.yml');

if(!is_array($config))
{
	echo "Could not load config/config.yml\n";
	exit();
}

$consumerKey = $config['twitter']['consumerKey'];
$consumerSecret = $config['twitter']['consumerSecret'];
$accessToken = $config['twitter']['accessToken'];
$accessTokenSecret = $config['twitter']['consumerTokenSecret'];

$twitter = new Twitter($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret);

// $r = $twitter->send("Hello, World");
// var_dump($r);

$args = $_SERVER['argv'];

if(count($args) < 2){
	echo "Missing path to input\n";
	exit();
}

$path = $args[1];
$fullPath = __DIR__.'/../'.$path;

if(!file_exists($fullPath)){
	echo "Could not find file at ".$fullPath."\n";
	exit();
}

echo "Found input\n";
echo "Building Markov Map\n";
$markov = new MarkovGenerator();
$markov->loadFromFile($fullPath);

echo "Generating Tweet\n";
$tweet = $markov->getStreamStartingWith("I", 140);

echo "Sending Tweet\n";
$twitter->send($tweet);

echo "Sent!\n";